### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by RegulusFen** [marcopavanello/pbr-materials#2] opened 2020-10-21 09:19 UTC
Hi guys, I have been using this addon for some time, it has always worked flawlessly, I recently started using blender 2.83 and installed the addon, it works as intended until I delete an object, upon doing so I receive a traceback error, I have un-installed and re-installed the addon but the error persists.....

`Traceback (most recent call last):
  File "C:\Users\fdrum\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\PBR Materials\__init__.py", line 81, in poll
    if bpy.context.object.active_material:
AttributeError: 'NoneType' object has no attribute 'active_material'

location: <unknown location>:-1

`

This occurs even if the object has a material.

Thank you for this amazing addon!

**Comment by macio97** [comment] 2020-10-24 09:27
Sorry, can't reproduce, are you trying with the 3.4 version?

**Comment by RegulusFen** [comment] 2020-10-24 11:13
![PBR_Materials 2020-10-24 071044](https://user-images.githubusercontent.com/44952499/97080315-63fb7b00-15c8-11eb-9c8d-021ec143a967.png)

**Comment by macio97** [comment] 2020-10-24 11:22
Ok 3.4 is fine. Please can you write the procedure step by step to reproduce the issue?

**Comment by RegulusFen** [comment] 2020-10-24 11:42
Open a new scene (fresh blend), create a cube, add and apply a material to the cube, delete the cube - Produces the error

[PBR_Materials_Traceback.zip](https://github.com/macio97/PBR-Materials/files/5432822/PBR_Materials_Traceback.zip)

**Comment by macio97** [comment] 2020-10-26 11:48
Ok i could reproduce now, thanks.
The problem could be easily fixed, but i won't fix it since we are deprecating the add-on itself, we are doing that because our aim is to make an asset manager in the future that will allow you to add these materials.
Thank you for reporting, but don't worry about the error for the moment.

**Comment by marcopavanello** [comment] 2021-06-23 10:36
Does the issue still appear with the new 3.5 release?

**Closed** 2022-01-05 14:30 UTC
